version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: maglo_dev
      POSTGRES_USER: maglo_user
      POSTGRES_PASSWORD: maglo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maglo_user -d maglo_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: dev
    environment:
      DATABASE_URL: postgresql://maglo_user:maglo_password@postgres:5432/maglo_dev
      JWT_SECRET: your-super-secret-jwt-key-for-development
      JWT_EXPIRES_IN: 7d
      NODE_ENV: development
      PORT: 4000
      FRONTEND_URL: http://localhost:3000
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: ["npm", "run", "dev:backend"]

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: dev
    environment:
      VITE_GRAPHQL_URL: http://localhost:4000/graphql
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    command: ["npm", "run", "dev:frontend"]

volumes:
  postgres_data:
